spring:
  mail:
    host: smtp.poczta.onet.pl
    port: 465
    username: ***@op.pl
    password: ***
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
